[project]
name = "pyweb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.4"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "uvicorn>=0.35.0",
]
